### ISSUE TITLE
ExecuteQuery: Dot notation doesn't work in Frends

### ISSUE THREAD

**Issue by Svenskapojkarna** [FrendsPlatform/Frends.MySql#11]
The task is returning the data in JToken format. The data type is set as JToken in definitions/Result.cs. In Frends returning a JToken as a result will prevent usage of dot notation in Frends. The Result has to return `dynamic` instead of `JToken` to enable usage of dot notation. Example: https://github.com/FrendsPlatform/Frends.Oracle/blob/master/Frends.Oracle.ExecuteQuery/Frends.Oracle.ExecuteQuery/Definitions/Result.cs#L24

**Comment by RikuVirtanen** [comment]
This has been fixed in PR #12
